name: "UniPi HomeAssistant bridge"
description: "UniPi device and their entities represented in Home Assistant with MQTT auto-discovery"
version: "0.1.0"
slug: "unipi_ha"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
options:
  mqtt: null
  unipi: []
schema:
  mqtt: str
  unipi:
    - str
